### ISSUE TITLE
Quick panel font

### ISSUE THREAD

**Issue by gpbl** [iccir/El-Capitan-Theme#11]
Is it possible to change the quick panel font to Helvetica as well? That Lucida feels a bit old now that I'm used to El-Capitan :-)

**Comment by iccir** [comment]
I'd love to make this change, but adding `"font.face": "Helvetica Neue"` to various quick panel rules in the theme file is having no effect :(

**Comment by gpbl** [comment]
Oh :( Thanks anyway!

**Comment by iccir** [comment]
I opened http://sublimetext.userecho.com/topic/773897-/ for this issue

**Comment by gpbl** [comment]
ah great thanks! Does the developer actually read that? 😅 well let see... with OS 10.11 Lucida Grande will become even more obsolete :-)

**Comment by iccir** [comment]
Hopefully he reads it! :)  If people could vote on it, that might help too!
