### ISSUE TITLE
Find buttons in Linux

### ISSUE THREAD

**Issue by jinhyunchoo** [iccir/El-Capitan-Theme#12]
Thank you for this nice theme. I have been looking for a nice light theme, and this is my favorite so far. One problem I found is, while it works perfectly in my OSX, the find buttons are not visible in my Linux (Ubuntu) as attached. Would you be able to fix this problem? Many thanks. ![el_capitan](https://cloud.githubusercontent.com/assets/4894819/7603292/7d66cf0a-f8e5-11e4-958e-806f3a110c7e.png)

**Comment by iccir** [comment]
I'm guessing this is the same issue as #8, which I don't have a fix for.  You might want to try installing the forked theme from that issue.

**Comment by jinhyunchoo** [comment]
Yes it was the same problem due to Helvetica Neue and the forked theme works good. Thank you for your help!

**Comment by iccir** [comment]
@jinhyunchoo - Can you try the new `el_capitan_font_default` setting. If set to true and you restart Sublime, no font will be set by the theme, which I believe will fix these issues.

**Comment by jinhyunchoo** [comment]
@iccir Thank you for the update. Yes I've found that now the issue has been resolved!
