### ISSUE TITLE
No names on side-bar files

### ISSUE THREAD

**Issue by jeanCarloMachado** [iccir/El-Capitan-Theme#8]
I installed the package from Package Control and it came this way.

http://i.imgur.com/pLdVvHj.png

**Comment by ig0r74** [comment]
Have the same problem on Xubuntu 14.04
http://i.imgur.com/wc0hymL.png

**Comment by iccir** [comment]
Thanks ig0r74!  I'm wondering if the space in Helvetica Neue is causing some kind of issue on Linux.

**Comment by fordarnold** [comment]
Same issue here... No folder and file names in my sidebar.
:heart: the theme though.

**Comment by iccir** [comment]
I've added a new `el_capitan_font_default` setting.  If set to true and you restart Sublime, no font will be set by the theme, which I believe will fix these issues.

**Comment by iccir** [comment]
Based on the feedback in #12, it sounds like `el_capitan_font_default` should fix this.
