### ISSUE TITLE
Revert Folder Icon Color

### ISSUE THREAD

**Issue by aaronmoodie** [iccir/El-Capitan-Theme#9]
Would you be able to include an option to revert to the blue folder icons? Not really digging the yellow.

Thanks!

**Comment by iccir** [comment]
Did you have folder icons via another theme?  Previously, El Capitan had no sidebar icons (either folders or files), but I mentioned in #3 how to add them via installing another package.

**Comment by aaronmoodie** [comment]
hey @iccir. No, not added any other folders. For some reason I thought there was Blue folders there before hand. Anyway, I'm going to close this as I've come around to the yellow. :+1:
